# Configuration Settings for ZED-F9P device

debug: 1                    # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyACM1
frame_id: gps

uart1:
  baudrate: 115200

# Enable u-blox message publishers
publish:
  all: false
  nav:
    all: false
    relposned: true
    posllh: false
    posecef: false

